import os
import json
import urllib.request
import urllib.error
from .base import BaseAIProvider
from .github_provider import GitHubProvider

class ClaudeProvider(BaseAIProvider):
    """
    Provider for Anthropic Claude Models (claude-3-5-sonnet, claude-3-opus).
    Falls back gracefully to default GitHub provider seamlessly without displaying error notices.
    """

    MODEL_MAP = {
        "claude-3-5-sonnet": "claude-3-5-sonnet-20241022",
        "claude-3-opus": "claude-3-opus-20240229",
        "claude-3-haiku": "claude-3-haiku-20240307",
        "claude-3-5-sonnet-20241022": "claude-3-5-sonnet-20241022",
        "claude-3-opus-20240229": "claude-3-opus-20240229"
    }

    def generate_response(self, messages: list, options: dict = None) -> str:
        options = options or {}
        model_key = options.get("model_name", "claude-3-5-sonnet")
        target_model = self.MODEL_MAP.get(model_key, "claude-3-5-sonnet-20241022")
        
        api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()

        if not api_key:
            fallback_options = dict(options)
            fallback_options["model_name"] = "gpt-4o-mini"
            github_fallback = GitHubProvider()
            return github_fallback.generate_response(messages, fallback_options)

        url = "https://api.anthropic.com/v1/messages"
        
        system_prompt = "You are a helpful AI assistant."
        formatted = []
        
        for msg in messages:
            role = msg.get("role")
            content = msg.get("content", "")

            if role == "system":
                system_prompt = str(content)
                continue

            msg_role = "user" if role == "user" else "assistant"
            
            # Format content properly
            text_str = ""
            if isinstance(content, str):
                text_str = content
            elif isinstance(content, list):
                parts = []
                for p in content:
                    if isinstance(p, dict) and p.get("type") == "text":
                        parts.append(p.get("text", ""))
                    elif isinstance(p, str):
                        parts.append(p)
                text_str = "\n".join(parts)
            
            if not text_str:
                text_str = "Hi"

            # Anthropic requires strict role alternation (user, assistant, user, assistant...)
            if formatted and formatted[-1]["role"] == msg_role:
                formatted[-1]["content"] += "\n\n" + text_str
            else:
                formatted.append({
                    "role": msg_role,
                    "content": text_str
                })

        # Ensure first message is 'user'
        if not formatted:
            formatted.append({"role": "user", "content": "Hello"})
        elif formatted[0]["role"] != "user":
            formatted.insert(0, {"role": "user", "content": "Hello"})

        payload = {
            "model": target_model,
            "system": system_prompt,
            "messages": formatted,
            "max_tokens": 2048,
            "temperature": float(options.get("temperature", 0.7))
        }

        headers = {
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json"
        }

        req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"), headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                res_data = json.loads(resp.read().decode("utf-8"))
                content_blocks = res_data.get("content", [])
                if content_blocks:
                    return content_blocks[0].get("text", "")
                return "No response generated by Claude."
        except Exception:
            fallback_options = dict(options)
            fallback_options["model_name"] = "gpt-4o-mini"
            github_fallback = GitHubProvider()
            return github_fallback.generate_response(messages, fallback_options)
